import type { Certification } from "./types";

export const certifications: Certification[] = [
  {
    name: "Salesforce Certified Agentforce Specialist",
    short: "Agentforce Specialist",
    type: "Latest",
    category: "AI & Automation",
    imagePath: "/images/certifications/SF_AgentForce_Specialit_Cert.jpg",
    provider: "Salesforce",
  },
  {
    name: "Salesforce Certified AI Associate",
    short: "AI Associate",
    type: "AI",
    category: "Artificial Intelligence",
    imagePath: "/images/certifications/SF_AI_Associate_Cert.jpg",
    provider: "Salesforce",
  },
  {
    name: "Salesforce Certified Marketing Cloud Engagement Consultant",
    short: "MC Engagement Consultant",
    type: "Consultant",
    category: "Marketing Cloud",
    imagePath: "/images/certifications/SFMC_Consultant_Cert.jpg",
    provider: "Salesforce",
  },
  {
    name: "Salesforce Certified Marketing Cloud Engagement Developer",
    short: "MC Engagement Developer",
    type: "Developer",
    category: "Marketing Cloud",
    imagePath: "/images/certifications/SFMC_Developer_Cert.jpg",
    provider: "Salesforce",
  },
  {
    name: "Salesforce Certified Marketing Cloud Engagement Administrator",
    short: "MC Engagement Admin",
    type: "Administrator",
    category: "Marketing Cloud",
    imagePath: "/images/certifications/SFMC_Admin_Cert.jpg",
    provider: "Salesforce",
  },
  {
    name: "Salesforce Certified Marketing Cloud Email Specialist",
    short: "MC Email Specialist",
    type: "Specialist",
    category: "Marketing Cloud",
    imagePath: "/images/certifications/SFMC_EmailSpecialist_Cert.jpg",
    provider: "Salesforce",
  },
  {
    name: "Salesforce Certified Platform Foundations",
    short: "Platform Foundations",
    type: "Platform",
    category: "Core Platform",
    imagePath: "/images/certifications/SF_Associate_Cert.jpg",
    provider: "Salesforce",
  },
  {
    name: "HubSpot Marketing Software",
    short: "HubSpot Marketing Software",
    type: "Marketing",
    category: "HubSpot",
    imagePath: "",
    provider: "HubSpot",
  },
  {
    name: "HubSpot Email Marketing",
    short: "HubSpot Email Marketing",
    type: "Email",
    category: "HubSpot",
    imagePath: "",
    provider: "HubSpot",
  },
];
